apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-02
spec:
  capacity:
    storage: 1G
  accessModes:
    - ReadOnlyMany
  local:
    path: /tmp/
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
          - {key: kubernetes.io/hostname, operator: In, values: [minikube]}
